### ISSUE TITLE
qidiruv

### ISSUE THREAD

**Issue by AbdunazarovU** [Otkirjon2001/Namanganliklar24#4]
Поиск input tagi yordamida yasalishi kerak, keyin Поиск degan yozuv placeholder yordamida yoziladi.

https://github.com/Otkirjon2001/Namanganliklar24/blob/563c29413e18d90b1d2fcf3152effc971cef13cc/index.html#L33-L35

**Comment by Otkirjon2001** [comment]
input tegini hali o'tganimiz yo'q
